//============================================================================
// John Dugger
// 03/03/2019
// Generated by this web site, added some code for null int's.
// http://json2csharp.com/
//============================================================================
using System.Collections.Generic;

namespace WebAPI.Models
{
    public class StudentData
    {
        public object ID { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public string City { get; set; }

        public override string ToString()
        {
            return ((ID == null)? "" : ID.ToString()) + "," + Name + "," + Address + "," + City;
        }
    }

    public class StudentDataRoot
    {
        public List<StudentData> StudentData { get; set; }
    }

}
